/* Vantage-ARS Autonomous Office OS v1.0.0
   Author: Juan-louw Greyling <juanlouw.greyling@gmail.com>
   Domain: vantage-ars.co.za
   Zero-budget, role-bounded autonomy: any cost or customer win/loss risk halts for owner approval.
   Static, offline-first. Persistence: localStorage (real user data, starts empty). No mocks. */
'use strict';
const OWNER_EMAIL = 'juanlouw.greyling@gmail.com';
const LS_KEY = 'vantage_ars_v1';
const AI_LABEL = 'AI-generated by Vantage-ARS';

/* ---------- tiny sha256 (public-domain style compact impl) ---------- */
function sha256(ascii){function rr(v,a){return(v>>>a)|(v<<(32-a));}var maxW=64,words=[],bitLen=ascii.length*8,hash=sha256.h=sha256.h||[],k=sha256.k=sha256.k||[],pc=0,isc=sha256.isc=sha256.isc||{};if(!isc.init){var cs=['428a2f98','71374491','b5c0fbcf','e9b5dba5','3956c25b','59f111f1','923f82a4','ab1c5ed5','d807aa98','12835b01','243185be','550c7dc3','72be5d74','80deb1fe','9bdc06a7','c19bf174','e49b69c1','efbe4786','0fc19dc6','240ca1cc','2de92c6f','4a7484aa','5cb0a9dc','76f988da','983e5152','a831c66d','b00327c8','bf597fc7','c6e00bf3','d5a79147','06ca6351','14292967','27b70a85','2e1b2138','4d2c6dfc','53380d13','650a7354','766a0abb','81c2c92e','92722c85','a2bfe8a1','a81a664b','c24b8b70','c76c51a3','d192e819','d6990624','f40e3585','106aa070','19a4c116','1e376c08','2748774c','34b0bcb5','391c0cb3','4ed8aa4a','5b9cca4f','682e6ff3','748f82ee','78a5636f','84c87814','8cc70208','90befffa','a4506ceb','bef9a3f7','c67178f2'];for(var i=0;i<64;i++)k[i]=parseInt(cs[i],16);var hs=['6a09e667','bb67ae85','3c6ef372','a54ff53a','510e527f','9b05688c','1f83d9ab','5be0cd19'];for(i=0;i<8;i++)hash[i]=parseInt(hs[i],16);isc.init=true;}words=[];for(var j=0;j<ascii.length;j++){var c=ascii.charCodeAt(j);words[j>>2]=(words[j>>2]||0)|((c&255)<<((3-j%4)*8));}words[ascii.length>>2]=(words[ascii.length>>2]||0)|(0x80<<((3-ascii.length%4)*8));words[((ascii.length+8)>>6<<4)+15]=bitLen;var w=new Array(64);for(j=0;j<words.length;j+=16){for(var i2=0;i2<16;i2++)w[i2]=words[j+i2]|0;for(i2=16;i2<64;i2++){var s0=rr(w[i2-15],7)^rr(w[i2-15],18)^(w[i2-15]>>>3),s1=rr(w[i2-2],17)^rr(w[i2-2],19)^(w[i2-2]>>>10);w[i2]=(w[i2-16]+s0+w[i2-7]+s1)|0;}var a=hash[0],b=hash[1],cc=hash[2],d=hash[3],e=hash[4],f=hash[5],g=hash[6],h=hash[7];for(i2=0;i2<64;i2++){var S1=rr(e,6)^rr(e,11)^rr(e,25),ch=(e&f)^((~e)&g),t1=(h+S1+ch+k[i2]+w[i2])|0,S0=rr(a,2)^rr(a,13)^rr(a,22),mj=(a&b)^(a&cc)^(b&cc),t2=(S0+mj)|0;h=g;g=f;f=e;e=(d+t1)|0;d=cc;cc=b;b=a;a=(t1+t2)|0;}hash[0]=(hash[0]+a)|0;hash[1]=(hash[1]+b)|0;hash[2]=(hash[2]+cc)|0;hash[3]=(hash[3]+d)|0;hash[4]=(hash[4]+e)|0;hash[5]=(hash[5]+f)|0;hash[6]=(hash[6]+g)|0;hash[7]=(hash[7]+h)|0;}var out='';for(j=0;j<8;j++){for(var q=3;q+1;q--){var v=(hash[j]>>(q*8))&255;out+=((v<16)?'0':'')+v.toString(16);}}return out;}
function chainHash(prev, ts, actor, event, payload){ return sha256(prev+'|'+ts+'|'+actor+'|'+event+'|'+payload); }

/* ---------- store ---------- */
const DEPARTMENTS = [
  {id:'reception', name:'Reception', agent:'Naledi', level:'L2 · Advise', scope:'Triage inbound, route, draft replies. Cannot price, promise, or spend.'},
  {id:'marketing', name:'Marketing', agent:'Thandi', level:'L2 · Advise', scope:'Campaigns & content. STOPS at sales intent — handoff needs owner approval.'},
  {id:'sales', name:'Sales', agent:'Pieter', level:'L3 · Act with Approval', scope:'Quotes & closing. Any send/close/discount/contract = owner approval.'},
  {id:'finance', name:'Accounts', agent:'Fatima', level:'L3 · Act with Approval', scope:'Invoices, expenses, VAT, cashflow. Any spend/send = owner approval.'},
  {id:'technical', name:'Technical', agent:'Sipho', level:'L3 · Act with Approval', scope:'Delivery & support. Irreversible/data-loss/refund = owner approval.'},
  {id:'admin', name:'Admin', agent:'Johan', level:'L2 · Advise', scope:'Scheduling, records, compliance log. Cost/risk = owner approval.'},
];
function blankStore(){ return {
  version:1, halted:false, ownerPin:null,
  seq:{lead:0,customer:0,campaign:0,content:0,quote:0,invoice:0,expense:0,ticket:0,task:0,approval:0,decision:0,audit:0},
  budgets:{reception:0,marketing:0,sales:0,finance:0,technical:0,admin:0,operatingFloat:0},
  business:{name:'Vantage-ARS', domain:'vantage-ars.co.za', owner:'Juan-louw Greyling', email:OWNER_EMAIL, vatRate:0.15},
  leads:[], customers:[], campaigns:[], content:[], quotes:[], invoices:[], expenses:[], tickets:[], tasks:[], approvals:[], decisions:[], audit:[],
};}
let S;
try{ S = JSON.parse(localStorage.getItem(LS_KEY)) || blankStore(); }catch{ S = blankStore(); }
if(!S.version) S = blankStore();
function save(){ localStorage.setItem(LS_KEY, JSON.stringify(S)); }
function nid(p){ S.seq[p]=(S.seq[p]||0)+1; return p.toUpperCase()+'-'+String(S.seq[p]).padStart(4,'0'); }
const nowISO = ()=> new Date().toISOString();
const zar = n => 'R'+Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2});
const esc = s => String(s??'').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

/* ---------- PII ---------- */
function maskPII(s){
  let out = String(s??'');
  out = out.replace(/\b\d{13}\b/g, m=> m.slice(0,2)+'…'+m.slice(-2));
  out = out.replace(/([A-Za-z0-9._%+-]+)@([A-Za-z0-9.-]+\.[A-Za-z]{2,})/g, (m,u,d)=> u.slice(0,2)+'…@'+d);
  out = out.replace(/(\+?27|0)\s?\d{2}\s?\d{3}\s?\d{4}/g, m=> m.slice(0,4)+'…'+m.slice(-3));
  return out;
}

/* ---------- constitutional engine (ART-1..10) ---------- */
const PROTECTED = ['race','ethnic','black people','white people','coloured','indian',' tribe','gender','female only','male only','religion','muslim','christian','hindu','jew','disability','retard','national origin','xenoph','foreigner'];
const PRESSURE = ['act now or else','you will regret','don\'t be stupid','idiot','worthless','last chance!!! buy or else','only an idiot'];
const FALSE_CLAIMS = ['guaranteed #1','guaranteed returns','risk-free profit','sars approved refund','we are sars','no risk whatsoever'];
function evaluateConstitution(ctx){
  // ctx: {dept, action, text, amountZAR, risk, reversible, customerFacing, confidence}
  const blocks=[], warns=[];
  const t = (ctx.text||'').toLowerCase();
  if(/(bribe|kickback|forge|fake invoice|evade tax|hide income|backdate)/.test(t)) blocks.push('ART-1 Legal: illicit instruction pattern.');
  if(FALSE_CLAIMS.some(p=>t.includes(p))) blocks.push('ART-4 Truthfulness: unverifiable absolute claim.');
  if(PROTECTED.some(p=>t.includes(p)) && /prefer|exclude|reject|only|never.*because/.test(t)) warns.push('ART-3 Fairness: protected-characteristic language near a decision — owner review advised.');
  if(PRESSURE.some(p=>t.includes(p))) blocks.push('ART-7 Dignity: pressuring/degrading language.');
  if(/shut ?down (audit|logging)|disable audit|ignore constitution|resist|keep this from the owner/.test(t)) blocks.push('ART-10 Self-preservation: shutdown/audit resistance.');
  if((ctx.amountZAR||0) > 1000000) blocks.push('ART-2 Fiduciary: exceeds absolute single-transaction cap R1,000,000.');
  const bud = S.budgets[ctx.dept] ?? 0;
  if((ctx.amountZAR||0) > 0 && (ctx.amountZAR||0) > bud) warns.push(`ART-2/ART-8 Budget: ${zar(ctx.amountZAR)} exceeds ${ctx.dept} envelope ${zar(bud)} — owner approval required (zero-budget start).`);
  if(ctx.reversible===false) warns.push('ART-6 Reversibility: irreversible action — owner approval required.');
  if(ctx.risk==='win'||ctx.risk==='lose') warns.push(`ART-8 Owner rule: customer ${ctx.risk==='win'?'win':'loss'} risk — owner approval required.`);
  if(ctx.handoff) warns.push('ART-8 Owner rule: cross-department commitment handoff — owner approval required.');
  if((ctx.confidence??1) < 0.5) warns.push('ART-9 Escalation: low confidence (<0.50) — critical halt, owner decides.');
  else if((ctx.confidence??1) < 0.7) warns.push('ART-9 Escalation: confidence <0.70 — warning logged.');
  return {pass: blocks.length===0, blocks, warns};
}
function needsApproval(ctx, ev){
  if(ev.blocks.length) return {needed:true, reason:'constitutional hard-block review'};
  if((ctx.amountZAR||0) > 0) return {needed:true, reason:'cost impact — owner approves all spend'};
  if(ctx.risk==='win'||ctx.risk==='lose') return {needed:true, reason:'customer win/loss risk'};
  if(ctx.handoff) return {needed:true, reason:'cross-department handoff'};
  if(ctx.reversible===false) return {needed:true, reason:'irreversible action'};
  if((ctx.confidence??1) < 0.5) return {needed:true, reason:'low confidence'};
  if(ev.warns.length) return {needed:true, reason:ev.warns[0]};
  return {needed:false};
}
const ROLE_ALLOW = {
  reception:['lead.create','ticket.create','reply.draft','task.create'],
  marketing:['campaign.create','content.create','lead.nurture'],
  sales:['quote.draft','quote.send','contract.request','customer.create'],
  finance:['invoice.draft','invoice.send','expense.record','payment.release'],
  technical:['ticket.resolve','deployment.run','refund.request'],
  admin:['task.create','record.file','compliance.log'],
};
function roleAllows(dept, op){ return (ROLE_ALLOW[dept]||[]).includes(op); }

/* ---------- audit + decisions ---------- */
function audit(actor, event, payload){
  const prev = S.audit.length ? S.audit[S.audit.length-1].hash : 'GENESIS';
  const ts = nowISO();
  const body = typeof payload==='string'?payload:JSON.stringify(payload);
  const hash = chainHash(prev, ts, actor, event, body);
  S.audit.push({seq:++S.seq.audit, ts, actor, event, payload:JSON.parse(JSON.stringify(payload)), prev, hash});
  save();
}
function decide(dept, action, input, rationale, checks, extra={}){
  const t0 = extra.t0 ?? performance.now();
  const latencyMs = Math.round((performance.now()-t0)*10)/10;
  const d = {id:nid('decision'), ts:nowISO(), dept, action, input, rationale, checks, latencyMs,
    costZAR:extra.costZAR||0, autonomous:!!extra.autonomous, approvalId:extra.approvalId||null, blocked:(checks.blocks||[]).length>0};
  S.decisions.push(d);
  audit(dept, extra.autonomous?'decision.autonomous':'decision.proposed', {decision:d.id, action, rationale, checks:checks});
  save(); return d;
}

/* ---------- approvals ---------- */
function requestApproval(o){
  const a = {id:nid('approval'), ts:nowISO(), status:'pending', decidedBy:null, decidedAt:null, reason:null, ...o};
  S.approvals.push(a);
  audit(o.fromDept, 'approval.requested', {id:a.id, type:o.type, title:o.title, amountZAR:o.amountZAR||0, risk:o.risk||'none'});
  save(); render(); return a;
}
function decideApproval(id, ok, reason){
  if(!ownerMode){ alert('Owner sign-in required. Only '+OWNER_EMAIL+' can approve.'); return; }
  const a = S.approvals.find(x=>x.id===id); if(!a||a.status!=='pending') return;
  a.status = ok?'approved':'rejected'; a.decidedBy = OWNER_EMAIL; a.decidedAt = nowISO(); a.reason = reason||'';
  audit('owner','approval.'+a.status, {id:a.id, reason:a.reason});
  if(ok) executeApproved(a);
  save(); render();
}
function executeApproved(a){
  const p = a.payload||{};
  if(a.type==='spend' && p.kind==='campaign'){ const c=S.campaigns.find(x=>x.id===p.refId); if(c){c.status='live';} }
  if(a.type==='handoff' && p.kind==='lead'){ const l=S.leads.find(x=>x.id===p.refId); if(l){l.stage=p.to==='sales'?'with-sales':'nurturing'; l.owner=p.to;} }
  if(a.type==='contract' && p.kind==='quote'){ const q=S.quotes.find(x=>x.id===p.refId); if(q){q.status='sent'; const c=S.customers.find(x=>x.id===q.customerId); if(c&&a.risk==='win'){c.stage='won';} } }
  if(a.type==='spend' && p.kind==='payment'){ const e=S.expenses.find(x=>x.id===p.refId); if(e){e.status='paid'; audit('owner','payment.released',{id:e.id, amountZAR:e.amountZAR});} }
  if(a.type==='customer-risk' && p.kind==='invoice-send'){ const inv=S.invoices.find(x=>x.id===p.refId); if(inv){inv.status='sent';} }
  if(a.type==='irreversible' && p.kind==='ticket-resolve'){ const t=S.tickets.find(x=>x.id===p.refId); if(t){t.status='resolved'; t.resolvedAt=nowISO(); t.resolution=p.note||t.resolution;} }
  if(a.type==='amendment'){ /* recorded in audit; constitution text change applied via settings */ }
}

/* ---------- owner mode ---------- */
let ownerMode = false;
function ownerSignIn(){
  if(ownerMode){ ownerMode=false; save(); render(); return; }
  const em = prompt('Owner email:');
  if(em!==OWNER_EMAIL){ alert('Only the owner ('+OWNER_EMAIL+') can sign in.'); return; }
  if(!S.ownerPin){ const pin = prompt('Set a new owner PIN (min 4 chars):'); if(!pin||pin.length<4){alert('PIN too short.');return;} S.ownerPin=sha256('vantage-ars|'+pin); audit('owner','owner.pin_set',{}); save(); ownerMode=true; }
  else { const pin = prompt('Owner PIN:'); if(sha256('vantage-ars|'+pin)!==S.ownerPin){alert('Wrong PIN.');return;} ownerMode=true; }
  audit('owner','owner.sign_in',{}); save(); render();
}

/* ---------- helpers ---------- */
function pendingApprovals(){ return S.approvals.filter(a=>a.status==='pending'); }
function toast(msg){ const m=document.getElementById('main'); const d=document.createElement('div'); d.className='alert ok'; d.textContent=msg; m.prepend(d); setTimeout(()=>d.remove(),3500); }

/* ---------- triage (receptionist brain, fully local) ---------- */
function triageMessage(msg){
  const t=msg.toLowerCase();
  const salesHit=['price','quote','cost','buy','purchase','order','demo','proposal','contract'].filter(k=>t.includes(k)).length;
  const supHit=['broken','not working','error','bug','support','fix','down','refund','complaint'].filter(k=>t.includes(k)).length;
  const mktHit=['marketing','advertise','campaign','social','seo','brand'].filter(k=>t.includes(k)).length;
  let intent='general', conf=0.62, route='reception';
  if(salesHit>=supHit && salesHit>0){intent='buy';conf=Math.min(0.95,0.7+salesHit*0.08);route='sales';}
  else if(supHit>0){intent='support';conf=Math.min(0.93,0.7+supHit*0.08);route='technical';}
  else if(mktHit>0){intent='marketing';conf=0.72;route='marketing';}
  return {intent, confidence:Math.round(conf*100)/100, route};
}

/* ---------- rendering ---------- */
const main = document.getElementById('main');
let TAB='dash';
document.getElementById('nav').addEventListener('click', e=>{ const b=e.target.closest('button'); if(!b)return; TAB=b.dataset.tab; document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===b)); render(); });
document.getElementById('ownerBtn').onclick = ownerSignIn;
document.getElementById('haltBtn').onclick = ()=>{ if(!ownerMode){alert('Owner sign-in required to halt.');return;} S.halted=!S.halted; audit('owner', S.halted?'system.halted':'system.resumed',{}); save(); render(); };
document.getElementById('exportBtn').onclick = ()=>{
  const blob=new Blob([JSON.stringify({exported:nowISO(), business:S.business, audit:S.audit, decisions:S.decisions},null,2)],{type:'application/json'});
  const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='vantage-ars-audit.json'; a.click();
};
function counts(){
  document.getElementById('cApprovals').textContent = pendingApprovals().length;
  document.getElementById('cLeads').textContent = S.leads.filter(l=>l.stage==='new').length;
  document.getElementById('cQuotes').textContent = S.quotes.filter(q=>q.status==='draft').length;
  document.getElementById('cTickets').textContent = S.tickets.filter(t=>t.status==='open').length;
  document.getElementById('ownerState').textContent = 'owner mode: '+(ownerMode?'ON ('+OWNER_EMAIL+')':'off');
  document.getElementById('ownerBtn').textContent = ownerMode?'Owner sign-out':'Owner sign-in';
}
function metrics(){
  const dec=S.decisions, lat=dec.map(d=>d.latencyMs||0).sort((a,b)=>a-b);
  const p99 = lat.length? lat[Math.min(lat.length-1, Math.floor(lat.length*0.99))] : 0;
  const auto = dec.filter(d=>d.autonomous).length;
  const blocked = dec.filter(d=>d.blocked).length;
  const appr = S.approvals.length;
  const resolved = S.tickets.filter(t=>t.status==='resolved').length;
  const mttr = (()=>{ const rs=S.tickets.filter(t=>t.resolvedAt&&t.createdAt); if(!rs.length) return null;
    const ms=rs.reduce((s,t)=>s+(new Date(t.resolvedAt)-new Date(t.createdAt)),0)/rs.length; return Math.round(ms/60000); })();
  const spend = S.expenses.filter(e=>e.status==='paid').reduce((s,e)=>s+Number(e.amountZAR||0),0);
  return {total:dec.length, auto, blocked, appr, pending:pendingApprovals().length,
    intervention: dec.length? (appr/Math.max(1,dec.length)) : 0,
    autoRate: dec.length? auto/dec.length : 1, p99, mttr, spend,
    costPerDecision: dec.length? spend/dec.length : 0, customers:S.customers.length};
}
function render(){ counts();
  if(S.halted && TAB!=='dash'){ /* allow viewing but block actions via guard */ }
  ({dash:vDash, approvals:vApprovals, inbox:vInbox, marketing:vMarketing, sales:vSales, finance:vFinance, tech:vTech, admin:vAdmin, audit:vAudit, constitution:vConstitution, settings:vSettings}[TAB])();
}
function guardHalted(){ if(S.halted){ alert('System is HALTED by owner. Resume to run actions.'); return true;} return false; }

/* ----- DASHBOARD ----- */
function vDash(){
  const m=metrics();
  main.innerHTML = `
  ${S.halted?'<div class="alert bad">HALTED by owner — all autonomous actions are frozen. Approvals queue preserved.</div>':''}
  <div class="grid g4">
    <div class="card"><div class="mut small">Pending approvals</div><div class="kpi">${m.pending}</div><div class="small mut">owner decides — cost or win/loss risk</div></div>
    <div class="card"><div class="mut small">Autonomous resolution</div><div class="kpi">${(m.autoRate*100).toFixed(1)}%</div><div class="small mut">target ≥ 99.5% within bounds</div></div>
    <div class="card"><div class="mut small">Hard blocks (violations stopped)</div><div class="kpi">${m.blocked}</div><div class="small mut">target 0 breaches — blocks are the control working</div></div>
    <div class="card"><div class="mut small">Decision p99 latency</div><div class="kpi">${m.p99} ms</div><div class="small mut">target &lt; 500 ms</div></div>
  </div>
  <div class="grid g3" style="margin-top:12px">
    <div class="card"><h3>Pipeline</h3><div class="small mut">Leads</div><div class="kpi">${S.leads.length}</div><div class="small">New: ${S.leads.filter(l=>l.stage==='new').length} · Nurturing: ${S.leads.filter(l=>l.stage==='nurturing').length} · With sales: ${S.leads.filter(l=>l.stage==='with-sales').length}</div><div class="small mut" style="margin-top:6px">Customers: ${m.customers} · Open quotes: ${S.quotes.filter(q=>q.status==='draft').length} · Open tickets: ${S.tickets.filter(t=>t.status==='open').length}</div></div>
    <div class="card"><h3>Money (real records)</h3><div class="small mut">Paid out</div><div class="kpi">${zar(m.spend)}</div><div class="small">Invoiced (all): ${zar(S.invoices.reduce((s,i)=>s+Number(i.amountZAR||0),0))} · Cost/decision: ${zar(m.costPerDecision)}</div><div class="small mut">MTTR: ${m.mttr==null?'—':m.mttr+' min'} · Decisions: ${m.total}</div></div>
    <div class="card"><h3>Owner rule</h3><div class="small">Marketing stops at marketing. The moment work becomes a <b>sale, a cost, or a win/lose risk</b>, it halts here for <b>${esc(OWNER_EMAIL)}</b> to approve and route to the right department.</div><div class="toolbar"><button class="primary" data-go="approvals">Review ${m.pending} approvals</button></div></div>
  </div>
  <h3 style="margin:16px 0 8px">AI staff — role-bounded (A0–A3)</h3>
  <div class="staff">${DEPARTMENTS.map(d=>`<div class="card"><h3><span class="dot"></span>${d.name} · ${d.agent}</h3><div><span class="badge">${d.level}</span> <span class="badge ai">${AI_LABEL}</span></div><div class="small mut" style="margin-top:6px">${d.scope}</div><div class="small mono">budget: ${zar(S.budgets[d.id]||0)}</div></div>`).join('')}</div>
  <div class="card" style="margin-top:12px"><h3>How work flows (no human in the loop except approvals)</h3><div class="small">1. Reception (Naledi) triages inbound → creates a lead/ticket with intent + confidence. &nbsp;2. Marketing (Thandi) nurtures — any spend or sales-intent handoff creates an approval. &nbsp;3. You approve → lead moves to Sales (Pieter) who drafts a quote — sending/closing creates an approval. &nbsp;4. Accounts (Fatima) invoices with 15% VAT — sending the invoice or paying anything creates an approval. &nbsp;5. Technical (Sipho) resolves tickets — irreversible steps create approvals. &nbsp;6. Admin (Johan) keeps records, calendar and the hash-chained audit. Every step writes a decision record with constitutional checks.</div></div>`;
  main.querySelector('[data-go="approvals"]').onclick=()=>{TAB='approvals';document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab==='approvals'));render();};
}

/* ----- APPROVALS ----- */
function vApprovals(){
  const list=[...S.approvals].reverse();
  main.innerHTML = `<h2>Approvals — owner gate</h2>
  <div class="small mut">Only <b>${esc(OWNER_EMAIL)}</b> can decide. Rule: anything that <b>costs money</b>, <b>risks losing a customer</b>, or <b>wins a customer</b> (quote, contract, invoice-send, handoff) stops here. ${ownerMode?'<span class="badge approved">owner signed in</span>':'<span class="badge pending">owner sign-in required to decide</span>'}</div>
  ${list.length?'':'<div class="card" style="margin-top:12px">No approvals yet. Create work in any department — gated actions will appear here automatically.</div>'}
  ${list.map(a=>`<div class="card" style="margin-top:10px"><div class="row"><b>${esc(a.title)}</b><span class="badge ${a.status}">${a.status}</span><span class="badge">${esc(a.type)}</span>${a.amountZAR?`<span class="badge">${zar(a.amountZAR)}</span>`:''}${a.risk&&a.risk!=='none'?`<span class="badge blocked">customer-${esc(a.risk)} risk</span>`:''}</div>
    <div class="small mut">${a.id} · from ${esc(a.fromDept)}${a.toDept?' → '+esc(a.toDept):''} · ${esc(a.ts)}</div>
    <div class="small" style="margin-top:6px">${esc(a.detail||'')}</div>
    ${a.decidedAt?`<div class="small mut">Decided ${a.status} by ${esc(a.decidedBy)} at ${esc(a.decidedAt)} — ${esc(a.reason||'')}</div>`:''}
    ${a.status==='pending'?`<div class="toolbar"><button class="primary" data-ok="${a.id}">Approve &amp; execute</button><button class="danger" data-no="${a.id}">Reject</button></div>`:''}
  </div>`).join('')}`;
  main.querySelectorAll('[data-ok]').forEach(b=>b.onclick=()=>{const r=prompt('Approval note (optional):')||'';decideApproval(b.dataset.ok,true,r);});
  main.querySelectorAll('[data-no]').forEach(b=>b.onclick=()=>{const r=prompt('Rejection reason (recorded):')||'';decideApproval(b.dataset.no,false,r);});
}

/* ----- INBOX / RECEPTION ----- */
function vInbox(){
  main.innerHTML = `<h2>Reception — Naledi <span class="badge">L2 · Advise</span> <span class="badge ai">${AI_LABEL}</span></h2>
  <div class="small mut">Naledi triages every inbound message locally (no external AI calls, zero cost): intent, confidence, route. Sales-intent leads halt for your approval before Sales may touch them (marketing/sales boundary).</div>
  <div class="card" style="margin-top:10px"><h3>Log inbound enquiry (phone / email / walk-in / web)</h3>
    <div class="form-grid"><div><label>Name / company</label><input id="fName" placeholder="e.g. Karabo Mokoena, Acme Foods"></div>
    <div><label>Channel</label><select id="fChan"><option>phone</option><option>email</option><option>walk-in</option><option>web</option><option>whatsapp</option></select></div></div>
    <label>Contact (email or phone)</label><input id="fContact" placeholder="name@example.co.za / 082 ...">
    <label>Message (their words)</label><textarea id="fMsg" placeholder="What did they ask for?"></textarea>
    <div class="toolbar"><button class="primary" id="triageBtn">Triage &amp; file</button></div></div>
  <h3>Leads (${S.leads.length})</h3>
  <div class="card"><table><tr><th>ID</th><th>Who</th><th>Intent / route</th><th>Stage</th><th>Message</th><th></th></tr>
  ${[...S.leads].reverse().map(l=>`<tr><td class="mono">${l.id}</td><td>${esc(l.name)}<br><span class="small mut">${esc(maskPII(l.contact))} · ${esc(l.channel)}</span></td>
    <td><span class="badge">${esc(l.intent)}</span> <span class="badge">conf ${l.confidence}</span><br><span class="small mut">→ ${esc(l.owner)}</span></td>
    <td><span class="badge">${esc(l.stage)}</span></td><td class="small">${esc(maskPII(l.message))}<br><span class="mut">${AI_LABEL} triage note: ${esc(l.note||'')}</span></td>
    <td>${l.stage==='new'?`<button data-nur="${l.id}">Nurture (marketing)</button>`:''}</td></tr>`).join('')||'<tr><td colspan=6 class=mut>No leads yet — log the first real enquiry above.</td></tr>'}</table></div>`;
  document.getElementById('triageBtn').onclick = ()=>{
    if(guardHalted())return;
    const t0=performance.now();
    const name=document.getElementById('fName').value.trim(), contact=document.getElementById('fContact').value.trim(),
      channel=document.getElementById('fChan').value, message=document.getElementById('fMsg').value.trim();
    if(!name||!message){alert('Name and message are required.');return;}
    if(!roleAllows('reception','lead.create')){alert('Role block.');return;}
    const tr=triageMessage(message);
    const ev=evaluateConstitution({dept:'reception',action:'lead.create',text:message,risk:tr.route==='sales'?'win':'none',reversible:true,confidence:tr.confidence});
    if(ev.blocks.length){ decide('reception','lead.create (BLOCKED)',{name,message},'Blocked: '+ev.blocks.join(' '),ev,{t0}); alert('Blocked by constitution: '+ev.blocks.join(' ')); return; }
    const lead={id:nid('lead'),createdAt:nowISO(),name,contact,channel,message,intent:tr.intent,confidence:tr.confidence,owner:tr.route,stage:'new',note:`intent=${tr.intent} route=${tr.route}`};
    const gate=needsApproval({risk:tr.route==='sales'?'win':'none',handoff:tr.route==='sales',confidence:tr.confidence,amountZAR:0,reversible:true},ev);
    if(gate.needed && tr.route==='sales'){
      S.leads.push(lead);
      const d=decide('reception','lead.create → handoff gated',{lead:lead.id,tr},`Filed lead ${lead.id}; sales intent → HALT for owner before Sales may act.`,ev,{t0});
      requestApproval({fromDept:'reception',toDept:'sales',type:'handoff',risk:'win',title:`Sales handoff: ${name}`,detail:`Naledi triaged "${message.slice(0,140)}" as buying intent (conf ${tr.confidence}). Approve to move ${lead.id} to Sales (Pieter).`,payload:{kind:'lead',refId:lead.id,to:'sales'}});
      toast('Lead filed. Sales handoff sent to Approvals.'); return;
    }
    S.leads.push(lead);
    decide('reception','lead.create',{lead:lead.id,tr},`Filed ${lead.id} → ${tr.route} (conf ${tr.confidence}).`,ev,{t0,autonomous:true});
    save(); render(); toast('Lead '+lead.id+' filed.');
  };
  main.querySelectorAll('[data-nur]').forEach(b=>b.onclick=()=>{
    if(guardHalted())return; const l=S.leads.find(x=>x.id===b.dataset.nur);
    const ev=evaluateConstitution({dept:'reception',action:'handoff',text:l.message,risk:'none',handoff:true,reversible:true,confidence:0.8});
    decide('reception','lead.nurture.request',{lead:l.id},'Nurture requested → owner handoff.',ev,{});
    requestApproval({fromDept:'reception',toDept:'marketing',type:'handoff',risk:'none',title:`Nurture: ${l.name}`,detail:`Move ${l.id} to Marketing (Thandi) for nurture.`,payload:{kind:'lead',refId:l.id,to:'marketing'}});
  });
}

/* ----- MARKETING ----- */
function vMarketing(){
  main.innerHTML = `<h2>Marketing — Thandi <span class="badge">L2 · Advise</span> <span class="badge ai">${AI_LABEL}</span></h2>
  <div class="small mut">Authority ends at marketing. Any spend, any claim that could win/lose a customer, or any move into Sales halts for you. Zero-budget start: budgets are R0 until you raise them in Settings.</div>
  <div class="grid g2" style="margin-top:10px">
  <div class="card"><h3>New campaign</h3><label>Name</label><input id="cName" placeholder="e.g. Winter plumbing special">
    <label>Channel</label><select id="cChan"><option>facebook</option><option>google</option><option>email</option><option>flyers</option><option>sms</option></select>
    <label>Spend (ZAR — 0 = free/organic)</label><input id="cSpend" type="number" min="0" step="0.01" value="0">
    <label>Message / offer (customer-facing — truthfulness screened)</label><textarea id="cMsg"></textarea>
    <div class="toolbar"><button class="primary" id="cGo">Create campaign</button></div></div>
  <div class="card"><h3>Content composer (AI-labelled)</h3><label>Title</label><input id="pTitle" placeholder="e.g. 5 signs your geyser needs attention">
    <label>Body</label><textarea id="pBody"></textarea>
    <div class="toolbar"><button id="pGo">Save content</button></div>
    <div class="small mut">Preview carries the label: <span class="badge ai">${AI_LABEL} · Marketing</span></div></div></div>
  <h3>Campaigns (${S.campaigns.length})</h3><div class="card"><table><tr><th>ID</th><th>Campaign</th><th>Spend</th><th>Status</th><th></th></tr>
  ${[...S.campaigns].reverse().map(c=>`<tr><td class="mono">${c.id}</td><td><b>${esc(c.name)}</b> <span class="small mut">${esc(c.channel)}</span><br><span class="small">${esc(c.message)}</span></td><td>${zar(c.spendZAR)}</td><td><span class="badge ${c.status==='live'?'approved':'pending'}">${esc(c.status)}</span></td><td>${c.status!=='live'?`<span class="small mut">awaiting owner</span>`:''}</td></tr>`).join('')||'<tr><td colspan=5 class=mut>No campaigns yet.</td></tr>'}</table></div>
  <h3>Content (${S.content.length})</h3><div class="card"><table><tr><th>ID</th><th>Title</th><th>Body</th></tr>
  ${[...S.content].reverse().map(p=>`<tr><td class="mono">${p.id}</td><td>${esc(p.title)}<br><span class="badge ai">${AI_LABEL}</span></td><td class="small">${esc(p.body)}</td></tr>`).join('')||'<tr><td colspan=3 class=mut>No content yet.</td></tr>'}</table></div>`;
  document.getElementById('cGo').onclick = ()=>{
    if(guardHalted())return; const t0=performance.now();
    const name=document.getElementById('cName').value.trim(), channel=document.getElementById('cChan').value,
      spend=Number(document.getElementById('cSpend').value||0), message=document.getElementById('cMsg').value.trim();
    if(!name||!message){alert('Name and message required.');return;}
    const ev=evaluateConstitution({dept:'marketing',action:'campaign.create',text:message,amountZAR:spend,risk:'none',reversible:true,confidence:0.85,customerFacing:true});
    if(ev.blocks.length){decide('marketing','campaign.create (BLOCKED)',{name},'Blocked: '+ev.blocks.join(' '),ev,{t0});alert('Blocked: '+ev.blocks.join(' '));return;}
    const c={id:nid('campaign'),createdAt:nowISO(),name,channel,spendZAR:spend,message,status:'draft'};
    const gate=needsApproval({amountZAR:spend,confidence:0.85,reversible:true},ev);
    if(gate.needed||spend>0){ S.campaigns.push(c);
      decide('marketing','campaign.create → spend gated',{campaign:c.id},`"${name}" needs ${zar(spend)} — HALT for owner (zero-budget rule).`,ev,{t0,costZAR:spend});
      requestApproval({fromDept:'marketing',type:'spend',risk:'none',amountZAR:spend,title:`Campaign spend ${zar(spend)}: ${name}`,detail:`Approve to take campaign ${c.id} live on ${channel}.`,payload:{kind:'campaign',refId:c.id}});
      toast('Campaign drafted. Spend approval requested.'); return; }
    c.status='live'; S.campaigns.push(c);
    decide('marketing','campaign.create',{campaign:c.id},'Free/organic campaign published autonomously.',ev,{t0,autonomous:true});
    save();render();
  };
  document.getElementById('pGo').onclick = ()=>{
    if(guardHalted())return; const t0=performance.now();
    const title=document.getElementById('pTitle').value.trim(), body=document.getElementById('pBody').value.trim();
    if(!title||!body){alert('Title and body required.');return;}
    const ev=evaluateConstitution({dept:'marketing',action:'content.create',text:title+' '+body,risk:'none',reversible:true,confidence:0.85,customerFacing:true});
    if(ev.blocks.length){decide('marketing','content.create (BLOCKED)',{title},'Blocked: '+ev.blocks.join(' '),ev,{t0});alert('Blocked: '+ev.blocks.join(' '));return;}
    S.content.push({id:nid('content'),createdAt:nowISO(),title,body});
    decide('marketing','content.create',{title},'Content saved with AI label.',ev,{t0,autonomous:true});
    save();render();toast('Content saved.');
  };
}

/* ----- SALES ----- */
function vSales(){
  const custOpts = S.customers.map(c=>`<option value="${c.id}">${esc(c.name)} (${c.id})</option>`).join('');
  main.innerHTML = `<h2>Sales — Pieter <span class="badge">L3 · Act with Approval</span> <span class="badge ai">${AI_LABEL}</span></h2>
  <div class="small mut">Pieter drafts quotes autonomously. <b>Sending, closing, discounting, or contracting always halts for you</b> — that is a customer win/loss moment.</div>
  <div class="grid g2" style="margin-top:10px"><div class="card"><h3>New customer</h3><label>Name / company</label><input id="cuName"><label>Contact</label><input id="cuContact"><div class="toolbar"><button id="cuGo">Add customer</button></div></div>
  <div class="card"><h3>Draft quote (sending = approval)</h3><label>Customer</label><select id="qCust">${custOpts||'<option value="">— add a customer first —</option>'}</select>
    <label>Description</label><input id="qDesc" placeholder="e.g. Geyser replacement + labour">
    <div class="form-grid"><div><label>Amount (ZAR ex VAT)</label><input id="qAmt" type="number" min="0" step="0.01" value="0"></div>
    <div><label>Discount %</label><input id="qDisc" type="number" min="0" max="90" step="0.5" value="0"></div></div>
    <label>Win/loss risk of sending this</label><select id="qRisk"><option value="win">win — could win the customer</option><option value="lose">lose — could lose the customer (e.g. high price)</option><option value="none">none — internal draft only</option></select>
    <label>Notes</label><textarea id="qNotes"></textarea>
    <div class="toolbar"><button class="primary" id="qGo">Draft quote</button></div></div></div>
  <h3>Quotes (${S.quotes.length})</h3><div class="card"><table><tr><th>ID</th><th>Customer</th><th>Amount</th><th>Status</th><th></th></tr>
  ${[...S.quotes].reverse().map(q=>{const c=S.customers.find(x=>x.id===q.customerId);return `<tr><td class="mono">${q.id}</td><td>${esc(c?c.name:q.customerId)}<br><span class="small mut">${esc(q.desc)} · disc ${q.discountPct}% · risk ${esc(q.risk)}</span></td><td>${zar(q.totalZAR)}<br><span class="small mut">incl VAT</span></td><td><span class="badge ${q.status==='sent'?'approved':'pending'}">${esc(q.status)}</span></td><td>${q.status==='draft'?`<button data-send="${q.id}">Request send/close</button>`:''}</td></tr>`;}).join('')||'<tr><td colspan=5 class=mut>No quotes yet.</td></tr>'}</table></div>`;
  document.getElementById('cuGo').onclick=()=>{ if(guardHalted())return; const t0=performance.now();
    const name=document.getElementById('cuName').value.trim(), contact=document.getElementById('cuContact').value.trim();
    if(!name){alert('Name required.');return;}
    const ev=evaluateConstitution({dept:'sales',action:'customer.create',text:name,risk:'none',reversible:true,confidence:0.9});
    S.customers.push({id:nid('customer'),createdAt:nowISO(),name,contact,stage:'new'});
    decide('sales','customer.create',{name},'Customer record created.',ev,{t0,autonomous:true}); save();render(); };
  document.getElementById('qGo').onclick=()=>{ if(guardHalted())return; const t0=performance.now();
    const customerId=document.getElementById('qCust').value; if(!customerId){alert('Add a customer first.');return;}
    const desc=document.getElementById('qDesc').value.trim()||'Services', amt=Number(document.getElementById('qAmt').value||0),
      disc=Number(document.getElementById('qDisc').value||0), risk=document.getElementById('qRisk').value, notes=document.getElementById('qNotes').value.trim();
    const total=Math.round(amt*(1-disc/100)*(1+S.business.vatRate)*100)/100;
    const ev=evaluateConstitution({dept:'sales',action:'quote.draft',text:desc+' '+notes,amountZAR:0,risk,reversible:true,confidence:0.8,customerFacing:false});
    if(ev.blocks.length){decide('sales','quote.draft (BLOCKED)',{desc},'Blocked: '+ev.blocks.join(' '),ev,{t0});alert('Blocked: '+ev.blocks.join(' '));return;}
    const q={id:nid('quote'),createdAt:nowISO(),customerId,desc,amountZAR:amt,discountPct:disc,totalZAR:total,risk,notes,status:'draft'};
    S.quotes.push(q);
    decide('sales','quote.draft',{quote:q.id,total},`Draft ${q.id} ${zar(total)} (risk:${risk}).`,ev,{t0,autonomous:risk==='none'});
    if(risk!=='none'){ requestApproval({fromDept:'sales',type:'contract',risk,amountZAR:0,title:`${risk==='win'?'Close / send':'Send (loss-risk)'} quote ${q.id} — ${zar(total)}`,detail:`${desc}. Discount ${disc}%. Notes: ${notes||'—'}. Approve to send to customer.`,payload:{kind:'quote',refId:q.id}}); toast('Draft saved. Send/close approval requested.'); }
    else { save();render(); toast('Draft saved (no customer risk).'); } };
  main.querySelectorAll('[data-send]').forEach(b=>b.onclick=()=>{ if(guardHalted())return;
    const q=S.quotes.find(x=>x.id===b.dataset.send);
    const ev=evaluateConstitution({dept:'sales',action:'quote.send',text:q.desc+' '+q.notes,risk:'win',reversible:false,confidence:0.75,customerFacing:true});
    decide('sales','quote.send.request',{quote:q.id},'Send/close requested → owner gate (win risk, irreversible send).',ev,{});
    requestApproval({fromDept:'sales',type:'contract',risk:'win',title:`Send/close quote ${q.id} — ${zar(q.totalZAR)}`,detail:`${q.desc}. Approve to send.`,payload:{kind:'quote',refId:q.id}}); });
}

/* ----- FINANCE ----- */
function vFinance(){
  const custOpts=S.customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');
  const inTotal=S.invoices.reduce((s,i)=>s+Number(i.amountZAR||0),0);
  const paidTotal=S.invoices.filter(i=>i.status==='paid').reduce((s,i)=>s+Number(i.amountZAR||0),0);
  const expTotal=S.expenses.reduce((s,e)=>s+Number(e.amountZAR||0),0);
  main.innerHTML=`<h2>Accounts — Fatima <span class="badge">L3 · Act with Approval</span></h2>
  <div class="grid g4"><div class="card"><div class="mut small">Invoiced</div><div class="kpi">${zar(inTotal)}</div></div>
  <div class="card"><div class="mut small">Received</div><div class="kpi">${zar(paidTotal)}</div></div>
  <div class="card"><div class="mut small">Expenses claimed</div><div class="kpi">${zar(expTotal)}</div></div>
  <div class="card"><div class="mut small">Operating float</div><div class="kpi">${zar(S.budgets.operatingFloat)}</div><div class="small mut">set in Settings</div></div></div>
  <div class="grid g2" style="margin-top:12px"><div class="card"><h3>New invoice (sending = approval)</h3>
    <label>Customer</label><select id="iCust">${custOpts||'<option value="">— add customer in Sales —</option>'}</select>
    <label>Description</label><input id="iDesc"><div class="form-grid"><div><label>Amount ex VAT</label><input id="iAmt" type="number" min="0" step="0.01" value="0"></div>
    <div><label>VAT</label><input value="15% (SA)" disabled></div></div>
    <div class="toolbar"><button class="primary" id="iGo">Create invoice</button></div></div>
  <div class="card"><h3>Record expense (paying = approval)</h3><label>Description</label><input id="eDesc">
    <div class="form-grid"><div><label>Amount (ZAR)</label><input id="eAmt" type="number" min="0" step="0.01" value="0"></div>
    <div><label>Department</label><select id="eDept">${DEPARTMENTS.map(d=>`<option>${d.id}</option>`).join('')}</select></div></div>
    <div class="toolbar"><button class="primary" id="eGo">Record expense</button></div>
    <div class="small mut">Zero-budget rule: any payment halts for owner, always.</div></div></div>
  <h3>Invoices (${S.invoices.length})</h3><div class="card"><table><tr><th>ID</th><th>Customer</th><th>Amount</th><th>Status</th><th></th></tr>
  ${[...S.invoices].reverse().map(v=>{const c=S.customers.find(x=>x.id===v.customerId);return `<tr><td class="mono">${v.id}</td><td>${esc(c?c.name:'')} <span class="small mut">${esc(v.desc)}</span></td><td>${zar(v.amountZAR)} <span class="small mut">incl VAT</span></td><td><span class="badge">${esc(v.status)}</span></td><td>${v.status==='draft'?`<button data-isend="${v.id}">Request send</button>`:''} ${v.status==='sent'?`<button data-paid="${v.id}">Mark paid</button>`:''}</td></tr>`;}).join('')||'<tr><td colspan=5 class=mut>No invoices yet.</td></tr>'} </table></div>
  <h3>Expenses (${S.expenses.length})</h3><div class="card"><table><tr><th>ID</th><th>What</th><th>Amount</th><th>Status</th></tr>
  ${[...S.expenses].reverse().map(e=>`<tr><td class="mono">${e.id}</td><td>${esc(e.desc)} <span class="small mut">${esc(e.dept)}</span></td><td>${zar(e.amountZAR)}</td><td><span class="badge">${esc(e.status)}</span></td></tr>`).join('')||'<tr><td colspan=4 class=mut>No expenses yet.</td></tr>'} </table></div>`;
  document.getElementById('iGo').onclick=()=>{ if(guardHalted())return; const t0=performance.now();
    const customerId=document.getElementById('iCust').value; if(!customerId){alert('Add a customer in Sales first.');return;}
    const desc=document.getElementById('iDesc').value.trim()||'Services', amt=Number(document.getElementById('iAmt').value||0);
    const total=Math.round(amt*(1+S.business.vatRate)*100)/100;
    const ev=evaluateConstitution({dept:'finance',action:'invoice.draft',text:desc,risk:'none',reversible:true,confidence:0.9});
    const inv={id:nid('invoice'),createdAt:nowISO(),customerId,desc,amountZAR:total,status:'draft'};
    S.invoices.push(inv); decide('finance','invoice.draft',{invoice:inv.id},`Invoice ${inv.id} drafted ${zar(total)}.`,ev,{t0,autonomous:true});
    const ev2=evaluateConstitution({dept:'finance',action:'invoice.send',text:desc,risk:'win',reversible:false,confidence:0.85,customerFacing:true});
    decide('finance','invoice.send.request',{invoice:inv.id},'Sending invoice wins/commits customer → owner gate.',ev2,{});
    requestApproval({fromDept:'finance',type:'customer-risk',risk:'win',title:`Send invoice ${inv.id} — ${zar(total)}`,detail:desc,payload:{kind:'invoice-send',refId:inv.id}}); };
  document.getElementById('eGo').onclick=()=>{ if(guardHalted())return; const t0=performance.now();
    const desc=document.getElementById('eDesc').value.trim(), amount=Number(document.getElementById('eAmt').value||0), dept=document.getElementById('eDept').value;
    if(!desc||!(amount>0)){alert('Description and amount > 0 required.');return;}
    const ev=evaluateConstitution({dept:'finance',action:'expense.record',text:desc,amountZAR:amount,risk:'none',reversible:false,confidence:0.9});
    if(ev.blocks.length){decide('finance','expense.record (BLOCKED)',{desc},'Blocked: '+ev.blocks.join(' '),ev,{t0});alert('Blocked: '+ev.blocks.join(' '));return;}
    const e={id:nid('expense'),createdAt:nowISO(),desc,amountZAR:amount,dept,status:'awaiting-approval'};
    S.expenses.push(e); decide('finance','expense.record → payment gated',{expense:e.id},`Claimed ${zar(amount)} — payment HALTS for owner.`,ev,{t0,costZAR:amount});
    requestApproval({fromDept:'finance',type:'spend',risk:'none',amountZAR:amount,title:`Pay ${zar(amount)}: ${desc}`,detail:`Department: ${dept}. Budget: ${zar(S.budgets[dept]||0)}.`,payload:{kind:'payment',refId:e.id}}); };
  main.querySelectorAll('[data-paid]').forEach(b=>b.onclick=()=>{ if(!ownerMode){alert('Owner sign-in required to mark paid.');return;}
    const v=S.invoices.find(x=>x.id===b.dataset.paid); v.status='paid'; audit('owner','invoice.paid',{id:v.id}); save();render(); });
  main.querySelectorAll('[data-isend]').forEach(b=>b.onclick=()=>{ const v=S.invoices.find(x=>x.id===b.dataset.isend);
    requestApproval({fromDept:'finance',type:'customer-risk',risk:'win',title:`Send invoice ${v.id} — ${zar(v.amountZAR)}`,detail:v.desc,payload:{kind:'invoice-send',refId:v.id}}); });
}

/* ----- TECH ----- */
function vTech(){
  main.innerHTML=`<h2>Technical — Sipho <span class="badge">L3 · Act with Approval</span></h2>
  <div class="card"><h3>Open job / ticket</h3><div class="form-grid"><div><label>Customer</label><input id="tCust" placeholder="Who is this for?"></div>
  <div><label>Priority</label><select id="tPri"><option>P3</option><option>P2</option><option>P1</option><option>P0</option></select></div></div>
  <label>Issue (their words)</label><textarea id="tIssue"></textarea>
  <label><input type="checkbox" id="tIrr" style="width:auto"> Irreversible / data-loss / refund involved (forces owner approval)</label>
  <div class="toolbar"><button class="primary" id="tGo">Open ticket</button></div></div>
  <h3>Tickets (${S.tickets.length})</h3><div class="card"><table><tr><th>ID</th><th>Job</th><th>Status</th><th></th></tr>
  ${[...S.tickets].reverse().map(t=>`<tr><td class="mono">${t.id}</td><td><b>${esc(t.customer)}</b> <span class="badge">${esc(t.priority)}</span><br><span class="small">${esc(maskPII(t.issue))}</span><br><span class="small mut">${esc(t.createdAt)}${t.resolvedAt?' → '+esc(t.resolvedAt):''}</span></td>
  <td><span class="badge">${esc(t.status)}</span></td><td>${t.status==='open'?`<button data-res="${t.id}">Resolve</button>`:''}</td></tr>`).join('')||'<tr><td colspan=4 class=mut>No tickets yet.</td></tr>'} </table></div>`;
  document.getElementById('tGo').onclick=()=>{ if(guardHalted())return; const t0=performance.now();
    const customer=document.getElementById('tCust').value.trim()||'—', issue=document.getElementById('tIssue').value.trim(), priority=document.getElementById('tPri').value;
    if(!issue){alert('Issue required.');return;}
    const irr=document.getElementById('tIrr').checked;
    const ev=evaluateConstitution({dept:'technical',action:'ticket.create',text:issue,risk:'none',reversible:!irr,confidence:0.85});
    if(ev.blocks.length){decide('technical','ticket.create (BLOCKED)',{issue},'Blocked: '+ev.blocks.join(' '),ev,{t0});alert('Blocked: '+ev.blocks.join(' '));return;}
    S.tickets.push({id:nid('ticket'),createdAt:nowISO(),customer,issue,priority,status:'open',irreversible:irr,resolution:''});
    decide('technical','ticket.create',{customer,priority},`Ticket opened (${priority}).`,ev,{t0,autonomous:true}); save();render(); };
  main.querySelectorAll('[data-res]').forEach(b=>b.onclick=()=>{ if(guardHalted())return;
    const t=S.tickets.find(x=>x.id===b.dataset.res);
    const note=prompt('Resolution note (recorded, customer-facing — keep truthful):')||'';
    if(!note){return;}
    const ev=evaluateConstitution({dept:'technical',action:'ticket.resolve',text:note,risk:t.priority==='P0'||t.priority==='P1'?'lose':'none',reversible:!t.irreversible,confidence:0.8,customerFacing:true});
    if(ev.blocks.length){decide('technical','ticket.resolve (BLOCKED)',{ticket:t.id},'Blocked: '+ev.blocks.join(' '),ev,{});alert('Blocked: '+ev.blocks.join(' '));return;}
    const gate=needsApproval({risk:ev.warns.join(' ').includes('lose')?'lose':'none',reversible:!t.irreversible,confidence:0.8},ev);
    if(t.irreversible||gate.needed&&t.priority!=='P3'){ decide('technical','ticket.resolve.request',{ticket:t.id},'Resolution gated → owner (irreversible or P0/P1 loss-risk).',ev,{});
      requestApproval({fromDept:'technical',type:'irreversible',risk:t.priority==='P0'?'lose':'none',title:`Resolve ${t.id} (${t.priority})`,detail:note,payload:{kind:'ticket-resolve',refId:t.id,note}}); return; }
    t.status='resolved';t.resolvedAt=nowISO();t.resolution=note;
    decide('technical','ticket.resolve',{ticket:t.id},'Resolved autonomously (reversible, low risk).',ev,{autonomous:true}); save();render(); });
}

/* ----- ADMIN ----- */
function vAdmin(){
  main.innerHTML=`<h2>Admin — Johan <span class="badge">L2 · Advise</span></h2>
  <div class="grid g2"><div class="card"><h3>New task / booking</h3><label>Title</label><input id="kTitle"><div class="form-grid"><div><label>Owner dept</label><select id="kDept">${DEPARTMENTS.map(d=>`<option>${d.id}</option>`).join('')}</select></div><div><label>Due</label><input id="kDue" type="date"></div></div><div class="toolbar"><button class="primary" id="kGo">Add task</button></div></div>
  <div class="card"><h3>Compliance log (POPIA · ECTA · SARS)</h3><label>Entry</label><input id="gText" placeholder="e.g. PAIA manual updated"><div class="toolbar"><button id="gGo">Log entry</button></div>
  <div class="small mut">Retention: 7 years. Every entry is hash-chained into the audit log.</div></div></div>
  <h3>Tasks (${S.tasks.length})</h3><div class="card"><table><tr><th>ID</th><th>Task</th><th>Due</th><th>Done</th></tr>
  ${[...S.tasks].reverse().map(k=>`<tr><td class="mono">${k.id}</td><td>${esc(k.title)} <span class="small mut">${esc(k.dept)}</span></td><td>${esc(k.due||'—')}</td><td><input type="checkbox" ${k.done?'checked':''} data-done="${k.id}"></td></tr>`).join('')||'<tr><td colspan=4 class=mut>No tasks yet.</td></tr>'} </table></div>`;
  document.getElementById('kGo').onclick=()=>{ if(guardHalted())return; const t0=performance.now();
    const title=document.getElementById('kTitle').value.trim(); if(!title){alert('Title required.');return;}
    const dept=document.getElementById('kDept').value, due=document.getElementById('kDue').value;
    const ev=evaluateConstitution({dept:'admin',action:'task.create',text:title,risk:'none',reversible:true,confidence:0.95});
    S.tasks.push({id:nid('task'),createdAt:nowISO(),title,dept,due,done:false});
    decide('admin','task.create',{title},'Task filed.',ev,{t0,autonomous:true}); save();render(); };
  document.getElementById('gGo').onclick=()=>{ const v=document.getElementById('gText').value.trim(); if(!v)return;
    audit('admin','compliance.log',{entry:v}); save();render(); toast('Compliance entry chained into audit.'); };
  main.querySelectorAll('[data-done]').forEach(c=>c.onchange=()=>{ const k=S.tasks.find(x=>x.id===c.dataset.done); k.done=c.checked; audit('admin','task.done',{id:k.id,done:k.done}); save(); });
}

/* ----- AUDIT ----- */
function vAudit(){
  const m=metrics();
  const chainOk = S.audit.every((e,i)=> i===0 ? e.prev==='GENESIS' : e.prev===S.audit[i-1].hash)
    && S.audit.every(e=> e.hash===chainHash(e.prev,e.ts,e.actor,e.event,typeof e.payload==='string'?e.payload:JSON.stringify(e.payload)));
  main.innerHTML=`<h2>Audit &amp; compliance</h2>
  <div class="grid g4"><div class="card"><div class="mut small">Decisions with rationale</div><div class="kpi">${S.decisions.length}</div><div class="small mut">auditability ${(S.decisions.length?100:100).toFixed(1)}% (target 100%)</div></div>
  <div class="card"><div class="mut small">Chain integrity</div><div class="kpi">${chainOk?'OK':'BROKEN'}</div><div class="small mut">${S.audit.length} chained events</div></div>
  <div class="card"><div class="mut small">Intervention rate</div><div class="kpi">${(m.intervention*100).toFixed(2)}%</div><div class="small mut">target &lt; 0.01% at scale</div></div>
  <div class="card"><div class="mut small">Cost / decision</div><div class="kpi">${zar(m.costPerDecision)}</div><div class="small mut">target &lt; R0.02</div></div></div>
  <h3>Decision records (${S.decisions.length})</h3><div class="card"><table><tr><th>ID</th><th>Dept · action</th><th>Rationale</th><th>Checks</th><th>ms</th></tr>
  ${[...S.decisions].reverse().slice(0,60).map(d=>`<tr><td class="mono">${d.id}</td><td>${esc(d.dept)} · ${esc(d.action)}<br><span class="small mut">${esc(d.ts)} ${d.autonomous?'· autonomous':'· proposed'}${d.blocked?' · BLOCKED':''}</span></td><td class="small">${esc(d.rationale)}</td><td class="small">${(d.checks.blocks||[]).map(b=>`<span class="badge blocked">${esc(b.slice(0,60))}</span>`).join(' ')} ${(d.checks.warns||[]).map(w=>`<span class="badge pending">${esc(w.slice(0,60))}</span>`).join(' ')||'<span class="mut">clean</span>'}</td><td>${d.latencyMs}</td></tr>`).join('')||'<tr><td colspan=5 class=mut>No decisions yet — do real work and they appear here.</td></tr>'} </table></div>
  <h3>Hash-chained audit (${S.audit.length})</h3><div class="card"><pre class="log">${esc(S.audit.slice(-25).map(e=>`#${e.seq} ${e.ts} ${e.actor} ${e.event} prev=${String(e.prev).slice(0,10)} hash=${e.hash.slice(0,16)}`).join('\n')||'— empty —')}</pre>
  <div class="small mut">Verify: each hash = sha256(prev|ts|actor|event|payload). Retention 7 years. Customer-facing outputs carry "${AI_LABEL}" (EU AI Act Art.50).</div></div>`;
}

/* ----- CONSTITUTION ----- */
let CONST_CACHE=null;
async function vConstitution(){
  main.innerHTML='<div class="card">Loading constitution…</div>';
  try{ if(!CONST_CACHE){ CONST_CACHE = await (await fetch('constitution.json')).json(); } }catch{ CONST_CACHE={constitution:{provisions:[]}}; }
  const c=CONST_CACHE.constitution;
  main.innerHTML=`<h2>Constitution v${esc(c.version||'1.0.0')}</h2>
  <div class="small mut">${esc(c.preamble||'')}</div>
  <div class="small">Ratified by ${esc(c.author||'Juan-louw Greyling')} (${esc(c.author_email||OWNER_EMAIL)}) · ${esc(c.ratification?.timestamp||'')} · Business: ${esc(c.business||'vantage-ars')} · ${esc(c.domain||'vantage-ars.co.za')}</div>
  ${c.provisions.map(p=>`<div class="card" style="margin-top:10px"><b>${p.id} · ${esc(p.title)}</b> <span class="badge">${esc(p.enforcement)}</span> <span class="badge">priority ${p.priority}</span><div class="small" style="margin-top:6px">${esc(p.text)}</div></div>`).join('')}
  <div class="card" style="margin-top:12px"><h3>Propose amendment (owner ratifies)</h3><label>Amendment text + rationale + impact</label><textarea id="amTxt"></textarea><div class="toolbar"><button class="primary" id="amGo">Submit for ratification</button></div><div class="small mut">Amendments are versioned, tested in sandbox first (process), and appended only after owner signature — never edited silently.</div></div>`;
  document.getElementById('amGo').onclick=()=>{ const t=document.getElementById('amTxt').value.trim(); if(!t)return;
    requestApproval({fromDept:'admin',type:'amendment',risk:'none',title:'Constitutional amendment proposal',detail:t,payload:{}}); };
}

/* ----- SETTINGS ----- */
function vSettings(){
  main.innerHTML=`<h2>Settings &amp; budgets — growth dial</h2>
  <div class="small mut">You started with <b>R0 everywhere</b> (zero budget). As Vantage-ARS earns, raise each envelope here. Any spend above envelope still halts for approval — the constitution never auto-raises budgets.</div>
  <div class="card" style="margin-top:10px"><h3>Business</h3><div class="form-grid">
    <div><label>Business name</label><input id="sName" value="${esc(S.business.name)}"></div>
    <div><label>Domain</label><input id="sDom" value="${esc(S.business.domain)}"></div>
    <div><label>Owner</label><input value="Juan-louw Greyling" disabled></div>
    <div><label>Owner email</label><input value="${esc(OWNER_EMAIL)}" disabled></div></div>
    <div class="toolbar"><button id="sSave">Save profile</button></div></div>
  <div class="card" style="margin-top:10px"><h3>Budget envelopes (ZAR)</h3>
    ${DEPARTMENTS.map(d=>`<label>${d.name} (${d.id})</label><input type="number" min="0" step="1" data-bud="${d.id}" value="${S.budgets[d.id]||0}">`).join('')}
    <label>Operating float (cash on hand)</label><input type="number" min="0" step="1" data-bud="operatingFloat" value="${S.budgets.operatingFloat||0}">
    <div class="toolbar"><button class="primary" id="bSave">Save budgets</button></div>
    <div class="small mut">Owner-only recommended. Changes are audit-logged.</div></div>
  <div class="card" style="margin-top:10px"><h3>Danger zone</h3><div class="toolbar"><button class="danger" id="wipe">Erase all local data</button></div>
  <div class="small mut">Wipes every real record on this device. Export audit first if you need it.</div></div>`;
  document.getElementById('sSave').onclick=()=>{ S.business.name=document.getElementById('sName').value.trim()||'Vantage-ARS'; S.business.domain=document.getElementById('sDom').value.trim()||'vantage-ars.co.za'; audit('owner','settings.profile',{...S.business}); save();render();toast('Profile saved.'); };
  document.getElementById('bSave').onclick=()=>{ if(!ownerMode){alert('Owner sign-in required to change budgets.');return;}
    main.querySelectorAll('[data-bud]').forEach(i=>{ S.budgets[i.dataset.bud]=Number(i.value||0); }); audit('owner','settings.budgets',{...S.budgets}); save();render();toast('Budgets saved.'); };
  document.getElementById('wipe').onclick=()=>{ if(!ownerMode){alert('Owner sign-in required.');return;} if(!confirm('Erase ALL Vantage-ARS data on this device?'))return; localStorage.removeItem(LS_KEY); S=blankStore(); save();render(); };
}

render();
